### ISSUE TITLE
一些请教

### ISSUE THREAD

**Issue by yaolp123** [songxiw/3D_build#2]
Github作者：
   你好！ 最近在github上https://github.com/isongxw/3D_build  看了你的工程，感兴趣，但是有些不太理解，能够加QQ交流下吗？感谢你的回复~  我的QQ:3101759565 感谢添加。期待回复~

**Comment by yaolp123** [comment]
期待github作者回复~

**Comment by isongxw** [comment]
> Github作者： 你好！ 最近在github上https://github.com/isongxw/3D_build 看了你的工程，感兴趣，但是有些不太理解，能够加QQ交流下吗？感谢你的回复~ 我的QQ:3101759565 感谢添加。期待回复~

ok

**Comment by yaolp123** [comment]
作者 您好 没看到您添加啊。 我的QQ:3101759565
